steal(
    '//core/public/lib/jquery/jquery-1.11.0.js'
).then(
    '//core/public/lib/bootstrap-3.1.1-dist/js/bootstrap.js',
    '//core/public/lib/bootstrap-3.1.1-dist/css/bootstrap.css'
).then(
    'jquery/model/list',
    'jquery/controller',
    'jquery/view'
).then(
    '//core/lib/isn/isn.js'
).then(
    '//core/controllers/controllers.js',
    '//core/models/models.js',
    '//core/views/views.js',
    '//core/public/css/css.js'
);